apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: backend
          image: idealcod/notes-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: host.docker.internal     # подключение к Postgres на хосте
            - name: DB_NAME
              value: notes
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: pass
